### ISSUE TITLE
missing file?

### ISSUE THREAD

**Issue by ericlarson84** [MOLB7621/problem-set-4#1]
Not seeing the ```hg19.chrom.size``` in the ```/data``` folder or in our ```/data-sets``` repo.  The closest is the ````hg19.genome``` in ```/data-sets/bedtools```.  This file has what I'm assuming are chromosome sizes plus a few other things.

**Comment by jayhesselberth** [comment]
I added `hg19.chrom.sizes` to the `data/` directory; it's identical to `hg19.genome`.
