### ISSUE TITLE
Meme PS4

### ISSUE THREAD

**Issue by ericlarson84** [MOLB7621/problem-set-4#2]
Perhaps I did this wrong, but my input fasta file for the MEME analysis has 5551 entries.  It's causing MEME to choke pretty hard.  The first 1000 sites go pretty quickly, but then it takes hours for the rest to finish.
First, should I have 5551 sites?  I followed the workflow in the Readme.rmd and the peaks look good in the [genome browser](https://genome.ucsc.edu/cgi-bin/hgTracks?hgS_doOtherUser=submit&hgS_otherUserName=elarson006&hgS_otherUserSessionName=eric%20PS4).   but here's what I did

```
chr1seq=$data/hg19.chr1.fa
factorx=$data/factorx.chr1.fq.gz
seq=$data/hg19.chrom.sizes
summits=$root/NA_summits.bed

bowtie2-build $chr1seq hg19.chr1

bowtie2 -x hg19.chr1 -U $factorx \
        | samtools sort -o factorx.sort.bam

#peak calls
        macs2 callpeak -t factorx.sort.bam

#generate motifs
        bedtools slop -i $summits -g $seq -b 25 > factorx.peaks.bed
        bedtools getfasta -fi $chr1seq -bed factorx.peaks.bed -fo factorx.peaks.fa
        meme factorx.peaks.fa -nmotifs 1 -maxw 20 -minw 8 -dna -maxsize 1000000


meme-get-motif -id 1 < $root/meme_out/meme.txt
```

Is there a way to break up the analysis so that it does it in batches of ~1000 or so?
Or should I just queue up the job on Tesla and let it go overnight?

**Comment by jayhesselberth** [comment]
I would select 1000 sites at random using `shuf/gshuf`:

```
gshuf factorx.peaks.bed | head -n 1000 > factorx.peaks.rand1000.bed
```
and then get fasta and derive motifs from those.

You could try all 5000 on tesla, but not everyone will have access to the cluster and so selecting 1000 at random is a better general solution.

Those peaks have high SNR so I would expect a very nice motif to come out of meme.

**Comment by ericlarson84** [comment]
Thanks.  I remember now from class using ```shuf```.  Worked nicely (and only took 5 or so minutes) and got a motif match using TomTom

**Comment by jayhesselberth** [comment]
ok. closing this so no one can copy your code :).
